"""new fields in user model for about me and last seen

Revision ID: 500322c719f5
Revises: e8cfa53c4bf3
Create Date: 2020-03-02 10:18:04.907680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500322c719f5'
down_revision = 'e8cfa53c4bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
